# Generated by Django 6.0.6 on 2026-07-04 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoLiveReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('education_status', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Devam Ediyor', 'Devam Ediyor'), ('Eksik', 'Eksik'), ('Riskli', 'Riskli'), ('Beklemede', 'Beklemede')], default='Devam Ediyor', max_length=30, verbose_name='Eğitim Durumu')),
                ('uat_status', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Devam Ediyor', 'Devam Ediyor'), ('Eksik', 'Eksik'), ('Riskli', 'Riskli'), ('Beklemede', 'Beklemede')], default='Devam Ediyor', max_length=30, verbose_name='UAT Durumu')),
                ('data_migration_status', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Devam Ediyor', 'Devam Ediyor'), ('Eksik', 'Eksik'), ('Riskli', 'Riskli'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=30, verbose_name='Veri Aktarımı')),
                ('authorization_status', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Devam Ediyor', 'Devam Ediyor'), ('Eksik', 'Eksik'), ('Riskli', 'Riskli'), ('Beklemede', 'Beklemede')], default='Devam Ediyor', max_length=30, verbose_name='Yetkilendirme Kontrolü')),
                ('critical_open_request_status', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Devam Ediyor', 'Devam Ediyor'), ('Eksik', 'Eksik'), ('Riskli', 'Riskli'), ('Beklemede', 'Beklemede')], default='Riskli', max_length=30, verbose_name='Kritik Açık Kayıt')),
                ('overall_status', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Devam Ediyor', 'Devam Ediyor'), ('Eksik', 'Eksik'), ('Riskli', 'Riskli'), ('Beklemede', 'Beklemede')], default='Devam Ediyor', max_length=30, verbose_name='Genel Durum')),
                ('evaluation_note', models.TextField(blank=True, verbose_name='Değerlendirme Notu')),
                ('recommended_next_step', models.TextField(blank=True, verbose_name='Önerilen Sonraki Adım')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='go_live_readiness', to='core.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Canlı Geçiş Hazırlığı',
                'verbose_name_plural': 'Canlı Geçiş Hazırlıkları',
            },
        ),
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('record_number', models.CharField(max_length=20, unique=True, verbose_name='Kayıt No')),
                ('title', models.CharField(max_length=300, verbose_name='Talep Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('feedback_source', models.CharField(choices=[('Hastane Çalışanı', 'Hastane Çalışanı'), ('Hasta / Hasta Yakını', 'Hasta / Hasta Yakını'), ('Proje Ekibi', 'Proje Ekibi'), ('Teknik Ekip', 'Teknik Ekip'), ('Yönetici', 'Yönetici'), ('Çağrı Merkezi', 'Çağrı Merkezi'), ('Saha Ziyareti', 'Saha Ziyareti'), ('UAT Geri Bildirimi', 'UAT Geri Bildirimi')], max_length=50, verbose_name='Geri Bildirim Kaynağı')),
                ('process_area', models.CharField(choices=[('Talep ve Geri Bildirim Yönetimi', 'Talep ve Geri Bildirim Yönetimi'), ('Eğitim', 'Eğitim'), ('UAT', 'UAT'), ('Veri Aktarımı', 'Veri Aktarımı'), ('Yetkilendirme', 'Yetkilendirme'), ('Performans', 'Performans'), ('Canlı Geçiş', 'Canlı Geçiş'), ('Raporlama', 'Raporlama'), ('Operasyonel Kullanım', 'Operasyonel Kullanım')], max_length=60, verbose_name='İlgili Süreç')),
                ('priority', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek'), ('Acil', 'Acil')], default='Orta', max_length=20, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('Açık', 'Açık'), ('Devam Ediyor', 'Devam Ediyor'), ('Planlandı', 'Planlandı'), ('Tamamlandı', 'Tamamlandı')], default='Açık', max_length=30, verbose_name='Durum')),
                ('responsible_team', models.CharField(max_length=100, verbose_name='Sorumlu Ekip')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Kapanış Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('go_live_impact', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], default='Orta', max_length=20, verbose_name='Canlı Geçiş Etkisi')),
                ('has_workaround', models.BooleanField(default=False, verbose_name='Geçici Çözüm Var mı?')),
                ('affects_patient_or_user_safety', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], default='Düşük', max_length=20, verbose_name='Kullanıcı/Hasta Güvenliği Etkisi')),
                ('operational_impact', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], default='Orta', max_length=20, verbose_name='Operasyonel Etki')),
                ('risk_level', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], default='Orta', max_length=20, verbose_name='Risk Seviyesi')),
                ('internal_risk_score', models.PositiveIntegerField(default=0, verbose_name='Dahili Risk Skoru')),
                ('evaluated_factors', models.JSONField(blank=True, default=list, verbose_name='Değerlendirme Unsurları')),
                ('evaluation_note', models.TextField(blank=True, verbose_name='Sistem Değerlendirme Notu')),
                ('recommended_action', models.TextField(blank=True, verbose_name='Önerilen Aksiyon')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Kullanıcı')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Talep Kaydı',
                'verbose_name_plural': 'Talep Kayıtları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='İşlem')),
                ('details', models.TextField(blank=True, verbose_name='Detay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.requestrecord', verbose_name='Talep')),
            ],
            options={
                'verbose_name': 'Talep Aktivitesi',
                'verbose_name_plural': 'Talep Aktiviteleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionSupportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('finding', models.TextField(verbose_name='Bulgu')),
                ('recommendation', models.TextField(verbose_name='Öneri')),
                ('expected_effect', models.TextField(blank=True, verbose_name='Beklenen Etki')),
                ('priority', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek'), ('Acil', 'Acil')], default='Orta', max_length=20, verbose_name='Öncelik')),
                ('responsible_team', models.CharField(blank=True, max_length=100, verbose_name='Sorumlu Ekip')),
                ('status', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Devam Ediyor', 'Devam Ediyor'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Beklemede', max_length=30, verbose_name='Durum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarih')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.project', verbose_name='Proje')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='projects.requestrecord', verbose_name='İlgili Talep')),
            ],
            options={
                'verbose_name': 'Karar Destek Kaydı',
                'verbose_name_plural': 'Karar Destek Kayıtları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requestrecord',
            index=models.Index(fields=['project', 'status'], name='projects_re_project_981642_idx'),
        ),
        migrations.AddIndex(
            model_name='requestrecord',
            index=models.Index(fields=['project', 'risk_level'], name='projects_re_project_ddf897_idx'),
        ),
        migrations.AddIndex(
            model_name='requestrecord',
            index=models.Index(fields=['project', 'process_area'], name='projects_re_project_1d0e85_idx'),
        ),
        migrations.AddIndex(
            model_name='requestrecord',
            index=models.Index(fields=['project', 'due_date'], name='projects_re_project_a7f04d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestrecord',
            index=models.Index(fields=['record_number'], name='projects_re_record__55e6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionsupportrecord',
            index=models.Index(fields=['project', 'status'], name='projects_de_project_d35f56_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionsupportrecord',
            index=models.Index(fields=['project', 'due_date'], name='projects_de_project_f1e166_idx'),
        ),
    ]
