# Generated by Django 6.0.6 on 2026-07-05 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionsupportrecord',
            name='source',
            field=models.CharField(choices=[('Talep', 'Talep'), ('Proje Riski', 'Proje Riski'), ('UAT Bulgusu', 'UAT Bulgusu'), ('Canlı Geçiş Sonrası Metrik', 'Canlı Geçiş Sonrası Metrik'), ('Yönetici Değerlendirmesi', 'Yönetici Değerlendirmesi')], default='Yönetici Değerlendirmesi', max_length=40, verbose_name='Kaynak'),
        ),
        migrations.AddField(
            model_name='decisionsupportrecord',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Kaynak Anahtarı'),
        ),
        migrations.AlterField(
            model_name='decisionsupportrecord',
            name='finding',
            field=models.TextField(verbose_name='Tespit'),
        ),
        migrations.AlterField(
            model_name='decisionsupportrecord',
            name='recommendation',
            field=models.TextField(verbose_name='Önerilen Karar'),
        ),
        migrations.CreateModel(
            name='PostGoLiveMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('metric_name', models.CharField(max_length=200, verbose_name='Gösterge Adı')),
                ('metric_category', models.CharField(choices=[('Destek Operasyonu', 'Destek Operasyonu'), ('Kalite ve Tekrar', 'Kalite ve Tekrar'), ('Eğitim ve Kullanım', 'Eğitim ve Kullanım'), ('Performans ve SLA', 'Performans ve SLA'), ('Veri ve Yetkilendirme', 'Veri ve Yetkilendirme'), ('Kullanıcı Geri Bildirimi', 'Kullanıcı Geri Bildirimi')], max_length=60, verbose_name='Gösterge Kategorisi')),
                ('target_value', models.CharField(max_length=100, verbose_name='Hedef Değer')),
                ('current_value', models.CharField(max_length=100, verbose_name='Güncel Değer')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Birim')),
                ('status', models.CharField(choices=[('Hedefte', 'Hedefte'), ('Dikkat Gerekli', 'Dikkat Gerekli'), ('Hedef Altında', 'Hedef Altında')], max_length=30, verbose_name='Durum')),
                ('measurement_date', models.DateField(verbose_name='Ölçüm Tarihi')),
                ('responsible_team', models.CharField(max_length=100, verbose_name='Sorumlu Ekip')),
                ('evaluation_note', models.TextField(blank=True, verbose_name='Değerlendirme Notu')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_go_live_metrics', to='core.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Canlı Geçiş Sonrası Gösterge',
                'verbose_name_plural': 'Canlı Geçiş Sonrası Göstergeler',
                'ordering': ['-measurement_date', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='decisionsupportrecord',
            name='related_post_go_live_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='projects.postgolivemetric', verbose_name='İlgili Canlı Geçiş Göstergesi'),
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('title', models.CharField(max_length=300, verbose_name='Risk Başlığı')),
                ('description', models.TextField(verbose_name='Risk Açıklaması')),
                ('category', models.CharField(choices=[('Teknik', 'Teknik'), ('Operasyonel', 'Operasyonel'), ('Organizasyonel', 'Organizasyonel'), ('Canlı Geçiş', 'Canlı Geçiş'), ('UAT', 'UAT'), ('Veri Aktarımı', 'Veri Aktarımı'), ('Yetkilendirme', 'Yetkilendirme'), ('Eğitim', 'Eğitim'), ('Destek Kapasitesi', 'Destek Kapasitesi')], max_length=60, verbose_name='Risk Kategorisi')),
                ('probability', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], max_length=20, verbose_name='Olasılık')),
                ('impact', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], max_length=20, verbose_name='Etki Seviyesi')),
                ('risk_level', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], max_length=20, verbose_name='Risk Seviyesi')),
                ('mitigation_action', models.TextField(blank=True, verbose_name='Önleyici Aksiyon')),
                ('contingency_action', models.TextField(blank=True, verbose_name='Gerçekleşme Durumunda Aksiyon')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarih')),
                ('status', models.CharField(choices=[('Açık', 'Açık'), ('Devam Ediyor', 'Devam Ediyor'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Açık', max_length=30, verbose_name='Durum')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_risks', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_project_risks', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_risks', to='core.project', verbose_name='Proje')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_project_risks', to='projects.requestrecord', verbose_name='İlgili Talep')),
            ],
            options={
                'verbose_name': 'Proje Riski',
                'verbose_name_plural': 'Proje Riskleri',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='decisionsupportrecord',
            name='related_project_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='projects.projectrisk', verbose_name='İlgili Proje Riski'),
        ),
        migrations.CreateModel(
            name='UATRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('scenario_name', models.CharField(max_length=300, verbose_name='Senaryo Adı')),
                ('process_area', models.CharField(choices=[('Talep ve Geri Bildirim Yönetimi', 'Talep ve Geri Bildirim Yönetimi'), ('Eğitim', 'Eğitim'), ('UAT', 'UAT'), ('Veri Aktarımı', 'Veri Aktarımı'), ('Yetkilendirme', 'Yetkilendirme'), ('Performans', 'Performans'), ('Canlı Geçiş', 'Canlı Geçiş'), ('Raporlama', 'Raporlama'), ('Operasyonel Kullanım', 'Operasyonel Kullanım')], max_length=60, verbose_name='İlgili Süreç')),
                ('expected_result', models.TextField(verbose_name='Beklenen Sonuç')),
                ('actual_result', models.TextField(blank=True, verbose_name='Gerçekleşen Sonuç')),
                ('result_status', models.CharField(choices=[('Başarılı', 'Başarılı'), ('Başarısız', 'Başarısız'), ('Bloke', 'Bloke'), ('Tekrar Test Bekliyor', 'Tekrar Test Bekliyor')], max_length=30, verbose_name='Sonuç Durumu')),
                ('severity', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], default='Orta', max_length=20, verbose_name='Önem Düzeyi')),
                ('responsible_team', models.CharField(max_length=100, verbose_name='Sorumlu Ekip')),
                ('tester_name', models.CharField(blank=True, max_length=100, verbose_name='Test Eden')),
                ('tester_role', models.CharField(blank=True, max_length=100, verbose_name='Test Eden Rol')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Test Tarihi')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Çözüm Notu')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uat_records', to='core.project', verbose_name='Proje')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uat_records', to='projects.requestrecord', verbose_name='İlgili Talep')),
            ],
            options={
                'verbose_name': 'UAT Kaydı',
                'verbose_name_plural': 'UAT Kayıtları',
                'ordering': ['-test_date', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='decisionsupportrecord',
            name='related_uat_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='projects.uatrecord', verbose_name='İlgili UAT Kaydı'),
        ),
        migrations.AddIndex(
            model_name='postgolivemetric',
            index=models.Index(fields=['project', 'status'], name='projects_po_project_053cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='postgolivemetric',
            index=models.Index(fields=['project', 'measurement_date'], name='projects_po_project_a64d73_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['project', 'risk_level'], name='projects_pr_project_a64d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_7203b2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrisk',
            index=models.Index(fields=['project', 'due_date'], name='projects_pr_project_52172b_idx'),
        ),
        migrations.AddIndex(
            model_name='uatrecord',
            index=models.Index(fields=['project', 'result_status'], name='projects_ua_project_575d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='uatrecord',
            index=models.Index(fields=['project', 'severity'], name='projects_ua_project_9819d4_idx'),
        ),
    ]
