# Generated by Django 6.0.6 on 2026-07-12 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0002_decisionsupportrecord_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrecord',
            name='retest_status',
            field=models.CharField(blank=True, choices=[('Gerekli Değil', 'Gerekli Değil'), ('Bekliyor', 'Bekliyor'), ('Planlandı', 'Planlandı'), ('Tamamlandı', 'Tamamlandı'), ('Başarısız', 'Başarısız')], max_length=30, verbose_name='Tekrar Test Durumu'),
        ),
        migrations.AddField(
            model_name='requestrecord',
            name='root_cause_status',
            field=models.CharField(blank=True, choices=[('Beklemede', 'Beklemede'), ('Analiz Ediliyor', 'Analiz Ediliyor'), ('Tanımlandı', 'Tanımlandı'), ('Doğrulandı', 'Doğrulandı')], max_length=30, verbose_name='Kök Neden Durumu'),
        ),
        migrations.AddField(
            model_name='requestrecord',
            name='solution_note',
            field=models.TextField(blank=True, verbose_name='Çözüm Notu'),
        ),
        migrations.AddField(
            model_name='requestrecord',
            name='technical_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_requests', to=settings.AUTH_USER_MODEL, verbose_name='Teknik Sorumlu'),
        ),
        migrations.AddField(
            model_name='requestrecord',
            name='technical_status',
            field=models.CharField(blank=True, choices=[('Analiz Bekliyor', 'Analiz Bekliyor'), ('Çözüm Planlandı', 'Çözüm Planlandı'), ('Geliştirme Devam Ediyor', 'Geliştirme Devam Ediyor'), ('Test Bekliyor', 'Test Bekliyor'), ('Tekrar Test Bekliyor', 'Tekrar Test Bekliyor'), ('Çözüm Doğrulandı', 'Çözüm Doğrulandı'), ('Canlıya Hazır', 'Canlıya Hazır'), ('Tamamlandı', 'Tamamlandı'), ('Bloke', 'Bloke')], max_length=40, verbose_name='Teknik Durum'),
        ),
        migrations.AddField(
            model_name='uatrecord',
            name='retest_status',
            field=models.CharField(blank=True, choices=[('Gerekli Değil', 'Gerekli Değil'), ('Bekliyor', 'Bekliyor'), ('Planlandı', 'Planlandı'), ('Tamamlandı', 'Tamamlandı'), ('Başarısız', 'Başarısız')], max_length=30, verbose_name='Tekrar Test Durumu'),
        ),
        migrations.AddField(
            model_name='uatrecord',
            name='root_cause_note',
            field=models.TextField(blank=True, verbose_name='Kök Neden Notu'),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='category',
            field=models.CharField(choices=[('Teknik', 'Teknik'), ('Operasyonel', 'Operasyonel'), ('Organizasyonel', 'Organizasyonel'), ('Canlı Geçiş', 'Canlı Geçiş'), ('UAT', 'UAT'), ('Veri Aktarımı', 'Veri Aktarımı'), ('Yetkilendirme', 'Yetkilendirme'), ('Eğitim', 'Eğitim'), ('Destek Kapasitesi', 'Destek Kapasitesi'), ('Yazılım Hatası', 'Yazılım Hatası'), ('Performans', 'Performans'), ('Entegrasyon', 'Entegrasyon'), ('Raporlama', 'Raporlama'), ('Test/UAT', 'Test/UAT'), ('Canlı Geçiş Teknik Hazırlık', 'Canlı Geçiş Teknik Hazırlık'), ('Altyapı', 'Altyapı')], max_length=60, verbose_name='Risk Kategorisi'),
        ),
        migrations.CreateModel(
            name='ProjectCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('communication_type', models.CharField(choices=[('Mesaj', 'Mesaj'), ('Talimat', 'Talimat')], default='Mesaj', max_length=20, verbose_name='Tür')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('recipient_role', models.CharField(blank=True, max_length=30, verbose_name='Alıcı Rol')),
                ('priority', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek'), ('Acil', 'Acil')], default='Orta', max_length=20, verbose_name='Öncelik')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarih')),
                ('status', models.CharField(choices=[('Gönderildi', 'Gönderildi'), ('Görüldü', 'Görüldü'), ('Devam Ediyor', 'Devam Ediyor'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='Gönderildi', max_length=30, verbose_name='Durum')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('completion_note', models.TextField(blank=True, verbose_name='Tamamlanma Notu')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.project', verbose_name='Proje')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_communications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı Kullanıcı')),
                ('related_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='projects.decisionsupportrecord', verbose_name='İlgili Karar')),
                ('related_project_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='projects.projectrisk', verbose_name='İlgili Risk')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='projects.requestrecord', verbose_name='İlgili Talep')),
                ('related_uat_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='projects.uatrecord', verbose_name='İlgili UAT')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Proje İletişimi',
                'verbose_name_plural': 'Proje İletişimleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'communication_type'], name='projects_pr_project_16d06c_idx'), models.Index(fields=['project', 'status'], name='projects_pr_project_ee0602_idx')],
            },
        ),
    ]
