# Generated by Django 6.0.6 on 2026-07-04 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('approval_status', models.CharField(choices=[('Onay Bekliyor', 'Onay Bekliyor'), ('Onaylı', 'Onaylı'), ('Reddedildi', 'Reddedildi')], default='Onay Bekliyor', max_length=20, verbose_name='Onay Durumu')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('role', models.CharField(choices=[('Sistem Yöneticisi', 'Sistem Yöneticisi'), ('Proje Yöneticisi', 'Proje Yöneticisi'), ('Teknik Lider', 'Teknik Lider'), ('Yönetici', 'Yönetici')], max_length=30, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization', verbose_name='Kurum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Üyelik',
                'verbose_name_plural': 'Üyelikler',
                'indexes': [models.Index(fields=['organization', 'role'], name='accounts_me_organiz_91db9c_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
