# Generated by Django 6.0.6 on 2026-07-12 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('role', models.CharField(choices=[('Sistem Yöneticisi', 'Sistem Yöneticisi'), ('Proje Yöneticisi', 'Proje Yöneticisi'), ('Teknik Lider', 'Teknik Lider'), ('Yönetici', 'Yönetici')], max_length=30, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.project', verbose_name='Proje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Proje Üyeliği',
                'verbose_name_plural': 'Proje Üyelikleri',
                'indexes': [models.Index(fields=['project', 'role'], name='accounts_pr_project_8f6b41_idx'), models.Index(fields=['user', 'is_active'], name='accounts_pr_user_id_51df2e_idx')],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
